export const BUSINESS_CATEGORY_OPTIONS = [
  "Food & Beverage",
  "Healthcare",
  "Retail",
  "Beauty & Wellness",
  "Fitness",
  "Automotive",
  "Education",
  "Home Services",
  "Professional Services",
  "Travel & Hospitality",
  "Tech & Digital",
  "Events & Entertainment",
].map((label) => ({ label, value: label }));

export const BUSINESS_TYPES_BY_CATEGORY = {
  "Food & Beverage": [
    "Restaurant",
    "Cafe",
    "Coffee shop",
    "Bakery",
    "Fast food outlet",
    "Cloud kitchen",
    "Food truck",
    "Bar",
    "Pub",
    "Juice center",
    "Catering service",
  ],
  Healthcare: [
    "Dental clinic",
    "General clinic",
    "Pediatric clinic",
    "Dermatology clinic",
    "Diagnostic center",
    "Physiotherapy clinic",
    "Pharmacy",
    "Veterinary clinic",
  ],
  Retail: [
    "Clothing store",
    "Electronics store",
    "Grocery store",
    "Furniture store",
    "Bookstore",
    "Jewelry store",
    "Pet store",
    "Toy store",
  ],
  "Beauty & Wellness": [
    "Salon",
    "Barber shop",
    "Nail salon",
    "Spa",
    "Skincare clinic",
    "Beauty clinic",
    "Tattoo studio",
  ],
  Fitness: [
    "Gym",
    "Yoga studio",
    "Pilates studio",
    "Dance studio",
    "Martial arts studio",
    "Personal training studio",
  ],
  Automotive: [
    "Auto repair",
    "Auto detailing",
    "Car dealership",
    "Car rental",
    "Tire shop",
    "EV service center",
  ],
  Education: [
    "Coaching center",
    "Tutoring center",
    "Language school",
    "Training institute",
    "Music school",
    "Daycare",
  ],
  "Home Services": [
    "Interior design",
    "Construction company",
    "Roofing contractor",
    "Cleaning service",
    "Home decor store",
    "Property management",
  ],
  "Professional Services": [
    "Accounting firm",
    "Law firm",
    "Consulting firm",
    "Digital marketing agency",
    "Recruitment agency",
    "Architecture firm",
  ],
  "Travel & Hospitality": [
    "Travel agency",
    "Hotel",
    "Hostel",
    "Resort",
    "Tour operator",
    "Holiday planner",
  ],
  "Tech & Digital": [
    "Software company",
    "Web development agency",
    "Mobile app development agency",
    "UX design studio",
    "IT services company",
    "SaaS startup",
  ],
  "Events & Entertainment": [
    "Event management",
    "Wedding planner",
    "Photography studio",
    "Production house",
    "Entertainment venue",
    "Live music venue",
  ],
};
