export const BUSINESS_CATEGORY_OPTIONS = [
  "Food & Beverage",
  "Healthcare",
  "Retail",
  "Beauty & Wellness",
  "Fitness",
  "Automotive",
  "Education",
  "Home Services",
  "Professional Services",
  "Travel & Hospitality",
  "Tech & Digital",
  "Events & Entertainment",
  "Real Estate",
  "Financial Services",
  "Legal & Compliance",
  "Manufacturing & Industrial",
  "Logistics & Transportation",
  "Agriculture & Farming",
  "Pet Care",
  "Kids & Family",
  "Wedding & Celebrations",
  "Media & Marketing",
  "Repair & Maintenance",
  "Spiritual & Community",
  "Construction & Infrastructure",
  "Energy & Utilities",
  "Telecom & Connectivity",
  "Government & Public Services",
  "Import & Export",
  "Mining & Natural Resources",
  "Marine & Fisheries",
  "Aviation & Aerospace",
  "Printing & Publishing",
  "Security & Safety",
  "Waste Management & Recycling",
  "Franchise & Multi-Unit",
  "E-commerce & D2C",
  "Luxury & Lifestyle",
  "Sports & Recreation",
  "Elderly Care & Assisted Living",
  "Wholesale & Distribution",
  "Biotech & Life Sciences",
  "Pharmaceuticals",
  "Textile & Apparel Manufacturing",
  "Forestry & Wood Products",
  "Nonprofit & NGOs",
  "Coworking & Shared Spaces",
  "Laundry & Dry Cleaning",
  "Translation & Localization",
  "Call Center & BPO",
  "Facilities Management",
  "Funeral & Memorial Services",
  "Pawn & Secondhand Trade",
].map((label) => ({ label, value: label }));

export const BUSINESS_TYPES_BY_CATEGORY = {
  "Food & Beverage": [
    "Restaurant",
    "Cafe",
    "Coffee shop",
    "Specialty coffee roastery",
    "Bakery",
    "Pastry shop",
    "Dessert bar",
    "Fast food outlet",
    "Fine dining restaurant",
    "Casual dining restaurant",
    "Takeaway restaurant",
    "Cloud kitchen",
    "Food truck",
    "Bar",
    "Pub",
    "Brewpub",
    "Wine bar",
    "Juice center",
    "Smoothie bar",
    "Ice cream shop",
    "Bubble tea shop",
    "Meal prep service",
    "Catering service",
    "Corporate catering",
    "Tiffin service",
    "Organic food store",
    "Confectionery shop",
    "Steakhouse",
    "Seafood restaurant",
    "Vegan restaurant",
    "Vegetarian restaurant",
    "Breakfast cafe",
    "Tea house",
    "Bistro",
    "Deli",
    "Pizzeria",
    "Burger restaurant",
    "Sushi restaurant",
    "Shawarma outlet",
    "BBQ restaurant",
    "Buffet restaurant",
    "Sweet shop",
  ],
  Healthcare: [
    "Dental clinic",
    "General clinic",
    "Pediatric clinic",
    "Dermatology clinic",
    "Diagnostic center",
    "Eye clinic",
    "ENT clinic",
    "Orthopedic clinic",
    "Cardiology clinic",
    "Psychology clinic",
    "Mental health center",
    "Physiotherapy clinic",
    "Pharmacy",
    "Medical store",
    "Pathology lab",
    "Imaging center",
    "Rehabilitation center",
    "Veterinary clinic",
    "Dialysis center",
    "Oncology center",
    "Fertility clinic",
    "Neurology clinic",
    "Pain management clinic",
    "Urgent care center",
    "Home healthcare service",
    "Nursing service",
    "Ambulance service",
    "Telemedicine provider",
    "Occupational therapy center",
    "Speech therapy clinic",
    "Chiropractic clinic",
  ],
  Retail: [
    "Clothing store",
    "Fashion boutique",
    "Footwear store",
    "Sportswear store",
    "Electronics store",
    "Mobile store",
    "Computer store",
    "Grocery store",
    "Supermarket",
    "Organic grocery store",
    "Furniture store",
    "Home appliance store",
    "Bookstore",
    "Jewelry store",
    "Gift shop",
    "Stationery store",
    "Cosmetics store",
    "Department store",
    "Pet store",
    "Toy store",
    "Hardware store",
    "Paint store",
    "Kitchenware store",
    "Luggage store",
    "Baby products store",
    "Bicycle store",
    "Music instrument store",
    "Thrift store",
    "Antique store",
    "Perfume store",
    "Outlet store",
    "Convenience store",
    "Sports equipment store",
    "Art supplies store",
    "Lighting store",
  ],
  "Beauty & Wellness": [
    "Salon",
    "Barber shop",
    "Nail salon",
    "Spa",
    "Skincare clinic",
    "Beauty clinic",
    "Tattoo studio",
    "Makeup studio",
    "Hair transplant clinic",
    "Laser clinic",
    "Wellness center",
    "Ayurveda clinic",
    "Massage center",
    "Meditation center",
  ],
  Fitness: [
    "Gym",
    "Yoga studio",
    "Pilates studio",
    "Dance studio",
    "Martial arts studio",
    "Personal training studio",
    "Crossfit box",
    "Cycling studio",
    "Zumba studio",
    "Strength and conditioning center",
    "Fitness bootcamp",
    "Sports academy",
  ],
  Automotive: [
    "Auto repair",
    "Auto detailing",
    "Car dealership",
    "Car rental",
    "Tire shop",
    "EV service center",
    "Bike repair shop",
    "Motorcycle dealership",
    "Car wash",
    "Auto body shop",
    "Auto glass repair",
    "Vehicle inspection center",
    "Tow service",
  ],
  Education: [
    "Coaching center",
    "Tutoring center",
    "Language school",
    "Training institute",
    "Music school",
    "Daycare",
    "STEM academy",
    "Coding bootcamp",
    "Online academy",
    "Test prep center",
    "Preschool",
    "Art school",
    "Skill development center",
  ],
  "Home Services": [
    "Interior design",
    "Construction company",
    "Roofing contractor",
    "Cleaning service",
    "Home decor store",
    "Property management",
    "Plumbing service",
    "Electrical service",
    "Pest control service",
    "HVAC service",
    "Painting contractor",
    "Carpentry service",
    "Security system installer",
    "Solar panel installer",
  ],
  "Professional Services": [
    "Accounting firm",
    "Law firm",
    "Consulting firm",
    "Digital marketing agency",
    "Recruitment agency",
    "Architecture firm",
    "Business consulting agency",
    "Tax consultancy",
    "HR consultancy",
    "Brand strategy agency",
    "PR agency",
    "Virtual assistant agency",
    "BPO service provider",
  ],
  "Travel & Hospitality": [
    "Travel agency",
    "Hotel",
    "Hostel",
    "Resort",
    "Tour operator",
    "Holiday planner",
    "Homestay",
    "Vacation rental management",
    "Adventure travel company",
    "Visa consultancy",
    "Destination management company",
    "Cruise planner",
  ],
  "Tech & Digital": [
    "Software company",
    "Web development agency",
    "Mobile app development agency",
    "UX design studio",
    "IT services company",
    "SaaS startup",
    "Cloud consulting company",
    "Cybersecurity firm",
    "DevOps consulting agency",
    "AI automation agency",
    "Data analytics company",
    "No-code development agency",
    "Managed IT services provider",
    "Blockchain development company",
    "AR/VR studio",
    "Game development studio",
    "CRM implementation partner",
    "ERP consulting company",
    "QA testing services",
    "Product engineering services",
    "IT staffing company",
    "Digital transformation consultancy",
    "RPA automation agency",
  ],
  "Events & Entertainment": [
    "Event management",
    "Wedding planner",
    "Photography studio",
    "Production house",
    "Entertainment venue",
    "Live music venue",
    "DJ services",
    "Event decor service",
    "Artist management agency",
    "Podcast studio",
    "Video production studio",
    "Theater group",
    "Kids party planner",
  ],
  "Real Estate": [
    "Real estate agency",
    "Property broker",
    "Commercial real estate consultant",
    "Luxury property consultant",
    "Property valuation service",
    "Rental management company",
    "Real estate developer",
    "Land acquisition consultant",
  ],
  "Financial Services": [
    "Insurance agency",
    "Investment advisory",
    "Mortgage consultancy",
    "Loan consultancy",
    "Wealth management firm",
    "Stock brokerage",
    "Financial planner",
    "Bookkeeping service",
    "Fintech startup",
  ],
  "Legal & Compliance": [
    "Corporate law firm",
    "IP law firm",
    "Tax law consultancy",
    "Compliance advisory",
    "Contract drafting service",
    "Legal documentation center",
    "Notary service",
    "Trademark consultancy",
  ],
  "Manufacturing & Industrial": [
    "Textile manufacturer",
    "Packaging manufacturer",
    "Plastic products manufacturer",
    "Metal fabrication unit",
    "Machinery manufacturer",
    "Chemical manufacturer",
    "Furniture manufacturer",
    "Food processing unit",
    "OEM supplier",
  ],
  "Logistics & Transportation": [
    "Logistics company",
    "Freight forwarding company",
    "Courier service",
    "Last mile delivery service",
    "Warehouse service",
    "Cold chain logistics",
    "Packers and movers",
    "Transport company",
  ],
  "Agriculture & Farming": [
    "Organic farm",
    "Dairy farm",
    "Poultry farm",
    "Hydroponic farm",
    "Agri input store",
    "Seed supplier",
    "Farm equipment dealer",
    "Agri consultancy",
  ],
  "Pet Care": [
    "Pet grooming salon",
    "Pet boarding center",
    "Pet daycare",
    "Pet training center",
    "Pet bakery",
    "Pet accessories store",
    "Pet adoption center",
    "Mobile pet grooming",
  ],
  "Kids & Family": [
    "Children activity center",
    "Indoor play area",
    "Parenting coaching center",
    "Kids learning center",
    "Kids dance academy",
    "Kids art studio",
    "Maternity care center",
    "Family counseling center",
  ],
  "Wedding & Celebrations": [
    "Wedding photography",
    "Wedding videography",
    "Bridal makeup studio",
    "Wedding decor company",
    "Banquet hall",
    "Catering for weddings",
    "Invitation design studio",
    "Mehendi artist service",
  ],
  "Media & Marketing": [
    "Digital advertising agency",
    "Social media agency",
    "Content marketing studio",
    "SEO agency",
    "Influencer marketing agency",
    "Branding agency",
    "Copywriting studio",
    "Performance marketing agency",
    "Creative agency",
    "Media buying agency",
    "Affiliate marketing agency",
    "Video marketing agency",
    "Email marketing agency",
    "Marketing automation agency",
    "Podcast production agency",
    "Growth marketing studio",
    "Public relations consultancy",
  ],
  "Repair & Maintenance": [
    "Appliance repair service",
    "Computer repair shop",
    "Phone repair shop",
    "Watch repair service",
    "Shoe repair shop",
    "Furniture repair service",
    "AC repair service",
    "Generator maintenance service",
  ],
  "Spiritual & Community": [
    "Yoga retreat center",
    "Meditation center",
    "Life coaching center",
    "Community center",
    "Spiritual counseling center",
    "Holistic healing center",
    "Non-profit organization",
    "Religious service center",
    "Mindfulness coaching center",
    "Counseling NGO",
    "Volunteer organization",
    "Community foundation",
    "Support group center",
  ],
  "Construction & Infrastructure": [
    "Civil contractor",
    "Road construction company",
    "Bridge construction contractor",
    "Commercial builder",
    "Residential builder",
    "Project management consultancy",
    "Construction material supplier",
    "Scaffolding contractor",
    "Waterproofing contractor",
    "Demolition service",
    "Surveying service",
    "Landscape construction",
  ],
  "Energy & Utilities": [
    "Solar energy company",
    "Wind energy solutions",
    "Battery storage provider",
    "EV charging network",
    "Power backup solutions",
    "Electrical utility contractor",
    "Water treatment company",
    "Gas distribution service",
    "Energy audit consultancy",
    "Smart grid services",
  ],
  "Telecom & Connectivity": [
    "Internet service provider",
    "Telecom operator",
    "Fiber installation service",
    "Network infrastructure company",
    "VoIP service provider",
    "Satellite communication provider",
    "Data center network services",
    "Unified communication provider",
  ],
  "Government & Public Services": [
    "Public sector consultancy",
    "Municipal services contractor",
    "Citizen service center",
    "Government documentation center",
    "Public policy advisory",
    "Smart city solutions provider",
    "Public records digitization service",
  ],
  "Import & Export": [
    "Import-export company",
    "Customs clearance agent",
    "Global sourcing agency",
    "Trade compliance consultancy",
    "International procurement company",
    "Export documentation service",
    "Cross-border logistics provider",
  ],
  "Mining & Natural Resources": [
    "Mining contractor",
    "Mineral processing company",
    "Exploration services",
    "Quarry operations company",
    "Geological survey service",
    "Natural resources consultancy",
  ],
  "Marine & Fisheries": [
    "Seafood processing company",
    "Fish farm",
    "Aquaculture supplier",
    "Marine equipment supplier",
    "Boat repair yard",
    "Commercial fishing company",
    "Harbor logistics service",
  ],
  "Aviation & Aerospace": [
    "Aviation training academy",
    "Aircraft maintenance service",
    "Drone services company",
    "Aerospace components manufacturer",
    "Airport ground handling service",
    "Flight charter services",
  ],
  "Printing & Publishing": [
    "Commercial printing press",
    "Packaging printing service",
    "Digital printing studio",
    "Book publishing house",
    "Magazine publisher",
    "Newspaper publisher",
    "Print design studio",
  ],
  "Security & Safety": [
    "Private security agency",
    "CCTV installation service",
    "Cyber safety consultancy",
    "Fire safety equipment supplier",
    "Access control system provider",
    "Security guard training institute",
    "Alarm system installer",
  ],
  "Waste Management & Recycling": [
    "Waste collection service",
    "Recycling plant",
    "E-waste recycling company",
    "Plastic recycling service",
    "Paper recycling company",
    "Industrial waste management",
    "Hazardous waste disposal service",
  ],
  "Franchise & Multi-Unit": [
    "Franchise consultancy",
    "Franchise development agency",
    "Multi-unit operations consultancy",
    "Franchise legal advisory",
    "Franchise marketing agency",
    "Franchise training provider",
  ],
  "E-commerce & D2C": [
    "E-commerce brand",
    "D2C brand",
    "Online marketplace seller",
    "Shopify development agency",
    "Marketplace management service",
    "Fulfillment center",
    "Dropshipping business",
    "Subscription box company",
    "Product photography for ecommerce",
  ],
  "Luxury & Lifestyle": [
    "Luxury fashion boutique",
    "Luxury concierge service",
    "Premium travel planner",
    "Fine jewelry boutique",
    "Luxury car rental",
    "Premium home decor studio",
    "Luxury event planner",
  ],
  "Sports & Recreation": [
    "Sports club",
    "Cricket academy",
    "Football academy",
    "Swimming academy",
    "Tennis academy",
    "Indoor sports arena",
    "Adventure sports company",
    "Outdoor recreation center",
  ],
  "Elderly Care & Assisted Living": [
    "Assisted living center",
    "Elderly home care service",
    "Geriatric clinic",
    "Senior activity center",
    "Palliative care center",
    "Medical equipment for seniors",
    "Senior wellness program",
  ],
  "Wholesale & Distribution": [
    "FMCG wholesaler",
    "Electronics wholesaler",
    "Pharmaceutical distributor",
    "Food and beverage distributor",
    "Industrial supplies distributor",
    "Automotive parts wholesaler",
    "Building materials distributor",
    "Wholesale marketplace",
    "Import wholesale distributor",
  ],
  "Biotech & Life Sciences": [
    "Biotech research company",
    "Genomics lab",
    "Clinical research organization",
    "Medical device R&D company",
    "Life sciences consulting",
    "Bioinformatics company",
    "Diagnostic biotech startup",
    "Lab equipment supplier",
  ],
  Pharmaceuticals: [
    "Pharmaceutical manufacturer",
    "Drug formulation company",
    "Contract pharma manufacturer",
    "Pharma export company",
    "Pharma distribution company",
    "Generic medicine company",
    "Clinical trial site",
    "Pharmacovigilance services",
  ],
  "Textile & Apparel Manufacturing": [
    "Garment manufacturer",
    "Textile mill",
    "Fabric processing unit",
    "Knitting factory",
    "Dyeing and printing unit",
    "Apparel export house",
    "Fashion sourcing company",
    "Uniform manufacturer",
    "Leather goods manufacturer",
  ],
  "Forestry & Wood Products": [
    "Timber supplier",
    "Sawmill",
    "Plywood manufacturer",
    "Wood furniture components manufacturer",
    "Forestry consultancy",
    "Wood treatment plant",
    "Paper pulp supplier",
  ],
  "Nonprofit & NGOs": [
    "Nonprofit organization",
    "Charitable foundation",
    "Humanitarian NGO",
    "Education nonprofit",
    "Healthcare NGO",
    "Environmental NGO",
    "Community development NGO",
    "Social enterprise",
  ],
  "Coworking & Shared Spaces": [
    "Coworking space",
    "Managed office provider",
    "Shared office center",
    "Virtual office provider",
    "Meeting room rental",
    "Startup incubator",
    "Innovation hub",
  ],
  "Laundry & Dry Cleaning": [
    "Laundry service",
    "Dry cleaning service",
    "Commercial laundry service",
    "On-demand laundry app",
    "Laundry pickup and delivery",
    "Uniform laundry service",
    "Shoe cleaning service",
  ],
  "Translation & Localization": [
    "Translation agency",
    "Localization services company",
    "Interpretation services",
    "Subtitling services",
    "Transcription services",
    "Multilingual content agency",
    "Language QA services",
  ],
  "Call Center & BPO": [
    "Inbound call center",
    "Outbound call center",
    "Customer support BPO",
    "Technical support BPO",
    "Back-office outsourcing",
    "Data processing BPO",
    "Telemarketing services",
    "Contact center as a service",
  ],
  "Facilities Management": [
    "Facility management company",
    "Commercial housekeeping service",
    "Building maintenance services",
    "Security and facility services",
    "Electrical facility maintenance",
    "Plumbing maintenance services",
    "Industrial facility management",
  ],
  "Funeral & Memorial Services": [
    "Funeral home",
    "Cremation services",
    "Burial services",
    "Memorial planning services",
    "Funeral transport services",
    "Casket and urn supplier",
    "Grief counseling services",
  ],
  "Pawn & Secondhand Trade": [
    "Pawn shop",
    "Secondhand electronics store",
    "Used furniture store",
    "Thrift resale shop",
    "Pre-owned luxury goods store",
    "Refurbished gadgets store",
    "Consignment store",
  ],
};
