export const BUSINESS_TYPES = [
  {
    category: "Automotive",
    options: [
      "Auto Detailing",
      "Auto Repair",
      "Car Dealership",
      "Car Rental",
      "Electric Vehicle Service",
      "Motorcycle Repair",
      "Tire Shop",
    ],
  },
  {
    category: "Beauty & Personal Care",
    options: [
      "Barber Shop",
      "Beauty Clinic",
      "Hair Transplant Clinic",
      "Makeup Artist",
      "Nail Salon",
      "Salon",
      "Skincare Clinic",
      "Spa",
      "Tattoo Studio",
      "Wellness Studio",
    ],
  },
  {
    category: "Business Services",
    options: [
      "Accounting Firm",
      "Call Center",
      "Cleaning Service",
      "Consulting Firm",
      "Coworking Space",
      "Digital Marketing Agency",
      "HR Consultancy",
      "Legal Services",
      "Logistics Company",
      "Printing Service",
      "Recruitment Agency",
      "Security Service",
      "Virtual Office Provider",
    ],
  },
  {
    category: "Education & Training",
    options: [
      "Coaching Center",
      "Daycare",
      "Language School",
      "Music School",
      "STEM Academy",
      "Training Institute",
      "Tutoring Center",
    ],
  },
  {
    category: "Food & Hospitality",
    options: [
      "Bakery",
      "Cafe",
      "Catering Service",
      "Cloud Kitchen",
      "Hotel",
      "Hostel",
      "Restaurant",
      "Resort",
    ],
  },
  {
    category: "Healthcare",
    options: [
      "Chiropractic Clinic",
      "Dental Clinic",
      "Dermatology Clinic",
      "Diagnostic Center",
      "Eye Clinic",
      "General Clinic",
      "Hospital",
      "Medical Store",
      "Pediatric Clinic",
      "Pharmacy",
      "Physiotherapy Clinic",
      "Psychology Clinic",
      "Veterinary Clinic",
    ],
  },
  {
    category: "Home & Real Estate",
    options: [
      "Construction Company",
      "Furniture Store",
      "Home Decor",
      "Interior Design",
      "Property Management",
      "Real Estate",
      "Roofing Contractor",
    ],
  },
  {
    category: "Lifestyle & Fitness",
    options: [
      "Dance Studio",
      "Gym",
      "Martial Arts Studio",
      "Personal Training Studio",
      "Pilates Studio",
      "Yoga Studio",
    ],
  },
  {
    category: "Professional & Creative",
    options: [
      "Architecture Firm",
      "Event Management",
      "Fashion Boutique",
      "Jewelry Store",
      "Law Firm",
      "Photography Studio",
      "Software Company",
      "Travel Agency",
      "UX Design Studio",
      "Web Development Agency",
      "Mobile App Development Agency",
    ],
  },
  {
    category: "Retail & Local Commerce",
    options: [
      "Bookstore",
      "Electronics Store",
      "Florist",
      "Grocery Store",
      "Optical Store",
      "Pet Store",
      "Toy Store",
    ],
  },
];

const countryNamesRaw = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const BUSINESS_TYPE_OPTIONS = BUSINESS_TYPES.flatMap((group) =>
  group.options.map((option) => ({
    label: option,
    value: option,
    category: group.category,
  }))
).sort((a, b) => a.label.localeCompare(b.label));

export const BUSINESS_TYPE_MAP = {
  "Accounting Firm": "accounting",
  "Architecture Firm": "architect",
  "Auto Detailing": "car_wash",
  "Auto Repair": "car_repair",
  Bakery: "bakery",
  "Barber Shop": "hair_care",
  "Beauty Clinic": "beauty_salon",
  Bookstore: "book_store",
  Cafe: "cafe",
  "Car Dealership": "car_dealer",
  "Car Rental": "car_rental",
  "Catering Service": "meal_delivery",
  "Chiropractic Clinic": "doctor",
  "Cleaning Service": "laundry",
  "Cloud Kitchen": "meal_takeaway",
  "Coaching Center": "school",
  "Construction Company": "general_contractor",
  "Coworking Space": "point_of_interest",
  "Dance Studio": "gym",
  Daycare: "school",
  "Dental Clinic": "dentist",
  "Dermatology Clinic": "doctor",
  "Diagnostic Center": "hospital",
  "Digital Marketing Agency": "point_of_interest",
  "Electric Vehicle Service": "car_repair",
  "Electronics Store": "electronics_store",
  "Event Management": "point_of_interest",
  "Eye Clinic": "doctor",
  "Fashion Boutique": "clothing_store",
  Florist: "florist",
  "Furniture Store": "furniture_store",
  "General Clinic": "doctor",
  "Grocery Store": "grocery_or_supermarket",
  Gym: "gym",
  "Hair Transplant Clinic": "doctor",
  Hostel: "lodging",
  Hospital: "hospital",
  "Home Decor": "home_goods_store",
  Hotel: "lodging",
  "HR Consultancy": "point_of_interest",
  "Interior Design": "home_goods_store",
  "Jewelry Store": "jewelry_store",
  "Language School": "school",
  "Law Firm": "lawyer",
  "Legal Services": "lawyer",
  "Logistics Company": "moving_company",
  "Makeup Artist": "beauty_salon",
  "Martial Arts Studio": "gym",
  "Medical Store": "pharmacy",
  "Mobile App Development Agency": "point_of_interest",
  "Motorcycle Repair": "car_repair",
  "Music School": "school",
  "Nail Salon": "beauty_salon",
  "Optical Store": "store",
  "Pediatric Clinic": "doctor",
  "Personal Training Studio": "gym",
  Pharmacy: "pharmacy",
  "Pet Store": "pet_store",
  "Photography Studio": "point_of_interest",
  "Physiotherapy Clinic": "physiotherapist",
  "Pilates Studio": "gym",
  "Printing Service": "store",
  "Property Management": "real_estate_agency",
  "Psychology Clinic": "doctor",
  "Real Estate": "real_estate_agency",
  "Recruitment Agency": "point_of_interest",
  Restaurant: "restaurant",
  Resort: "lodging",
  "Roofing Contractor": "roofing_contractor",
  Salon: "beauty_salon",
  "Security Service": "point_of_interest",
  "Skincare Clinic": "beauty_salon",
  "Software Company": "point_of_interest",
  Spa: "spa",
  "STEM Academy": "school",
  "Tattoo Studio": "store",
  "Tire Shop": "car_repair",
  "Toy Store": "store",
  "Training Institute": "school",
  "Travel Agency": "travel_agency",
  "Tutoring Center": "school",
  "UX Design Studio": "point_of_interest",
  "Veterinary Clinic": "veterinary_care",
  "Virtual Office Provider": "point_of_interest",
  "Web Development Agency": "point_of_interest",
  "Wellness Studio": "spa",
  "Yoga Studio": "gym",
};

export const COUNTRY_OPTIONS = countryNamesRaw
  .slice()
  .sort((a, b) => a.localeCompare(b))
  .map((country) => ({ label: country, value: country }));

export const CITIES_BY_COUNTRY = {
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary"],
  France: ["Paris", "Lyon", "Marseille", "Toulouse"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
  India: ["Mumbai", "Delhi", "Bengaluru", "Hyderabad"],
  Indonesia: ["Jakarta", "Bandung", "Surabaya", "Medan"],
  Italy: ["Rome", "Milan", "Naples", "Turin"],
  Japan: ["Tokyo", "Osaka", "Nagoya", "Yokohama"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
  Singapore: ["Singapore"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Bern"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Leeds"],
  "United States": ["New York", "San Francisco", "Los Angeles", "Chicago"],
};

export const AREAS_BY_CITY = {
  Berlin: ["Mitte", "Kreuzberg", "Neukolln", "Prenzlauer Berg"],
  Munich: ["Altstadt", "Schwabing", "Maxvorstadt", "Haidhausen"],
  Hamburg: ["Altona", "Eimsbuttel", "St. Pauli", "HafenCity"],
  Frankfurt: ["Innenstadt", "Sachsenhausen", "Bockenheim", "Bornheim"],
  London: ["Soho", "Camden", "Canary Wharf", "Shoreditch"],
  Toronto: ["Downtown", "North York", "Scarborough", "Etobicoke"],
  Vancouver: ["Downtown", "Kitsilano", "Yaletown", "Mount Pleasant"],
  Montreal: ["Old Montreal", "Plateau", "Downtown", "Griffintown"],
  Dubai: ["Downtown", "Marina", "Jumeirah", "Business Bay"],
  "San Francisco": ["SoMa", "Mission", "Sunset", "Financial District"],
  Mumbai: ["Bandra", "Andheri", "Powai", "Lower Parel"],
  Delhi: ["Connaught Place", "Saket", "Dwarka", "Karol Bagh"],
  Bengaluru: ["Indiranagar", "Koramangala", "Whitefield", "Jayanagar"],
  Hyderabad: ["Gachibowli", "Hitech City", "Banjara Hills", "Kondapur"],
  Paris: ["Le Marais", "Montmartre", "La Defense", "Saint-Germain"],
  Madrid: ["Salamanca", "Chamberi", "Retiro", "Centro"],
};
